---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working." > /root/hello-world
  
  - name: Create yallo in /tmp
    file: path=/tmp/yallo state=touch
  
  - name: Install Apache
    yum: name=httpd state=latest
  
  - name: Create index.html
    shell: echo "Web is fucking working!" > /var/www/html/index.html
    
  - service:
    name: httpd
    state: started
  
  - service:
    name: httpd
    enabled: yes
    
  
